apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdftojpeg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdftojpeg
  template:
    metadata:
      labels:
        app: pdftojpeg
    spec:
      containers:
        - name: pdftojpeg
          image: devhsmtek/pdftojpeg:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 16080
            - containerPort: 16000
          resources:
            limits:
              memory: 128Mi
              cpu: "0.2"
            requests:
              memory: 16Mi
              cpu: "0.1"
---
apiVersion: v1
kind: Service
metadata:
  name: pdftojpeg
spec:
  type: LoadBalancer
  ports:
    - port: 16000
      targetPort: 16000
      name: http
    - port: 16080
      targetPort: 16080
      name: rest
  selector:
    app: pdftojpeg